name: format-check
on:
  push:
    branches:
      - master
      - release-*
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - uses: actions/checkout@v1
      - name: Format check
        shell: julia --color=yes {0}
        run: |
          using Pkg
          # If you update the version, also update the style guide docs.
          Pkg.add(PackageSpec(name="JuliaFormatter", version="1"))
          using JuliaFormatter
          format("src", verbose=true)
          format("test", verbose=true)
          format("docs", verbose=true)
          out = String(read(Cmd(`git diff`)))
          if isempty(out)
              exit(0)
          end
          @error "Some files have not been formatted !!!"
          write(stdout, out)
          exit(1)

# Workflow from https://github.com/jump-dev/JuMP.jl/blob/master/.github/workflows/format_check.yml